use_frameworks!

platform :ios, '8.0'

target 'FBRetainCycleDetector_Example' do
#  pod 'FBRetainCycleDetector'
 pod 'FBRetainCycleDetector',:git=>'https://github.com/fangtingchao/FBRetainCycleDetector.git',:tag => '0.1.1'
end
